### PR TITLE
[configurator] using ABC for cmake_var

### PR DESCRIPTION
**Pull request by michelececcacci**
Using an ABC instead of simply derivating. I feel like it reflects better what we are trying to do

### CODE REVIEW

**Review by vvaltchev — CHANGES_REQUESTED** [review]
I'm sorry if that might disappoint you, but this is textbook overengineering. The fact that ABCMeta exists, doesn't mean we have to use it for first trivial inheritance we introduced. Such libraries have been introduced to handle way more complicated cases in big projects. We have just one base class and two derived classes and you're already trying to most powerful tool available. It feels like when I used C++ metaprogramming techniques to solve minor problems just because it was cool :-)  

So, please: _do not use a cannon to kill a mosquito_ (Confucius)

**Comment by michelececcacci** [comment]
> I'm sorry if that might disappoint you, but this is textbook overengineering. The fact that ABCMeta exists, doesn't mean we have to use it for first trivial inheritance we introduced. Such libraries have been introduced to handle way more complicated cases in big projects. We have just one base class and two derived classes and you're already trying to most powerful tool available. It feels like when I used C++ metaprogramming techniques to solve minor problems just because it was cool :-)
> 
> So, please: _do not use a cannon to kill a mosquito_ (Confucius)

Should i use a normal ABC instead?

**Comment by vvaltchev** [comment]
@michelececcacci Sorry, but I genuinely believe the whole change should be dropped, in the name of the KISS principle. There is no real need to use the `abc` module at all, at the moment. I know it's cool and powerful, but it's also a huge overkill in this trivial case. Let's use it in case the complexity of the configurator tool raises significantly.

Again, don't get me wrong: I'm sure that with `abc` we could do powerful OOP, but do we really need that now? What we're gaining from it, in the current context? We're adding an unnecessary dependency to a fancy module (standard module, I know, but still) and we're just adding more syntax sugar. Using simple inheritance was reasonably the most "powerful solution" I was willing to accept and it already was a bit over-engineering. Declaring a whole abstract class I way too much.

A more pythonic solution would be do use a dict with `serialize()` functions, no classes, no objects :-) Doing every possible thing with OOP is overrated today.

**Comment by michelececcacci** [comment]
Ok, i think you are right.

**Pull request closed without merging**
