### PR TITLE
Issue #121 - move kernel/fs/fat32_debug.c to tests/unit/ - Pull Request

### PR DESCRIPTION
**Pull request by lvntky**
I moved to the : kernel/fs/fat32_debug.c to the tests/unit/ directory. I deleted the fat32_debug.c declarations from fat32_base.h, here is the lists of the declarations that i deleted from fat32_base.h:

```
void
fat_write_fat_entry(struct fat_hdr *h,
                    enum fat_type ft,
                    u32 fatN,
                    u32 clusterN,
                    u32 value);

u32 fat_get_cluster_count(struct fat_hdr *hdr);

bool fat32_is_valid_filename_character(char c);

size_t fat_get_file_size(struct fat_entry *entry);
```
After that I build the tilck on qemu and run gtests, I don't occur any problems.

### CODE REVIEW

**Review by vvaltchev — CHANGES_REQUESTED** [review]
Hello @lvntky, actually the only declaration that needs to be removed from fat32_base.h and moved into the unit tests is: `void fat_dump_info(void *fatpart_begin)` because it's the main debug function in fat32_debug.c. All the rest of the declarations you removed are actually useful and not part of some debug code. Please remove only that function declaration.

**Comment by lvntky** [comment]
I apologize for misunderstanding. And thank you very much for being patient :) I'm sure I won't make small mistakes like this in the future. thank you very much

**Comment by vvaltchev** [comment]
> I apologize for misunderstanding. And thank you very much for being patient :) I'm sure I won't make small mistakes like this in the future. thank you very much

No problem, @lvntky. It's definitively not OK to fix the problem by adding more commits. When you make a pull request, expect that the maintainer of the project will ask you to make changes for each one of those commits. To do that, you'll need to use the git interactive rebase feature (e.g. git rebase -i master) on your feature branch. After marking the commits you need to fix with 'e', git will enter in each one of those commits. There, you'll need to make the changes, commit with --amend and then continue with rebase --continue. 

In alternative, if you're not so confident with git, just make smaller changes and squash them all before creating the pull request. After that, you'll make the fixes and commit --amend and then post an update with git push --force. This is the simpler model we've been using with @michelececcacci.

**Comment by lvntky** [comment]
Thank you very much for your interest and patience. I built the tests and declared the test_dump_buf() function in the kernel_init_funcs.h library so that fat32_test.cpp did not give an error. Apart from that, I added the other declarations that I deleted unnecessarily to the fat32_base.h file. But i did not push the changes yet, i hope i did it right. I don't fully understand the git part, but I think I will adapt to the project in the future, if you want, I can create a cleaner pull request by deleting this pull request and doing what I mentioned above from scratch on new pr. Thank you again for your patience and interest. @vvaltchev

**Comment by vvaltchev** [comment]
No problem, @lvntky. 

Please, don't but that declaration in kernel_init_funcs.h, that header has a different purpose. Put the declaration in fat32_test.cpp. It's not a reusable functionality, so it doesn't need to be in a header.

Now, about the cleaner change. There's absolutely no need to create a new pull request. Just, learn to use git. First of all, when you create a patch, never work on the master branch. Create a custom branch on your own with git checkout -b YOUR_BRANCH_NAME. After that, commit with --amend, so that you'll re-write the commit instead of creating new ones and then do git push origin YOUR_BRANCH --force. This way, the pull request will be updated. For the moment, stick with this workflow while you learn to use git. But yeah, learning at least the bare minimum with git is essential to do any kind of contribution today. There are tons of tutorials online, I'm sure you'll find a tutorial you'll like. It's not hard, don't get scared ;-)

**Comment by lvntky** [comment]
HI @vvaltchev so i just moved fat_dump_info into the fat32_test.cpp and push as you told me so with --amend and --force. Also i ran gtests and don't occur any problem(passed 144 tests), But i don't know why the 2 checks failed. Sorry for bothering you for this easy job but i will be more efficient for further contributions and definitely will finish a git course :) thank you for your effort again

**Review by vvaltchev — CHANGES_REQUESTED** [review]
Thanks @lvntky! The change is close to be ready for merge. A few more things to fix:
 - a recent change of mine (in docs/) appears in your commit as well for some weird reason. Check the diff that github shows. To fix that:
     - pull the latest changes from master
     - checkout your topic branch with your commit
     - do: git rebase master, so that git will re-apply your changes on the top of master
     - then push your branch again with --force, of course
    
- also, now after the squash, the fix is overall correct, but the commit message is wrong: when you do commit --amend, you can also change the commit description. Make it be something like: `[gtests] Move kernel/fs/fat32_debug.c to tests/unit/`. Note the `[gtests]` tag. Most of the commits in Tilck have tags. I don't have an official list yet so, don't worry. Just, for this case the tag is `[gtests]`.

**Comment by vvaltchev** [comment]
@lvntky P.S. don't worry for this particular failure, it's unrelated with your changes.

**Comment by lvntky** [comment]
hi @vvaltchev , thank you for this great explanation, I rebase with master, added the `[gtests]` with --amend, and push with --force. Hope works this time :)

**Review by vvaltchev — APPROVED** [review]
That's perfect, thanks for fixing!

**Comment by lvntky** [comment]
really thank you so much @vvaltchev . It was very enjoyable for me and I learned a lot. I will be dealing with other issues in the future because I would like to contribute to tilck. but I'll get better git knowledge first :) thank you very much for your patience and helpfulness see you in the next issue :)

**Comment by vvaltchev** [comment]
No problem, @lvntky. I'm happy that you'd like to seriously contribute to this project: there are a lot of challenges and funny things to do here. Take your time to learn git and play a bit with Tilck.  From tomorrow, I'll be on vacation for about a week so I won't be able to review any pull requests, but there's no rush. The good thing about open source contributions is that, typically, there are no deadlines :-)

**Comment by vvaltchev** [comment]
Btw @lvntky, something weird happened: git shows your commit with my name, even on your branch in your repo. Actually, with `git log --pretty=full`, I see you as commiter, while me as author, while it should be exactly the opposite.

image

**Comment by vvaltchev** [comment]
@lvntky I fixed the issue by changing the author to "lvntky <klevent1903@gmail.com>" and doing a push --force on the master branch, thing that should _never_ be done... well, except if very rare cases, only on the latest commit and only if a very little time has passed since the commit has been pushed. Not sure what went wrong here. 

Next time you do pull from master, do `pull --rebase`, otherwise you'll get a conflict because of `my push --force` to fix this issue.

**Comment by lvntky** [comment]
@vvaltchev Thank you very much for handling it. i `pull --rebase` minute ago, and i should do it before starting my next commit i guess. I wish you a nice and happy vacation :) I will continue to work on tilck and git as you said, hope to see you after your holiday.

**Pull request merged**
